- hosts: all
  tasks:
  - name: Install common tools
    pacman:
      name: "{{ packages }}"
    vars:
      packages:
        - masscan
        - openvpn
        - metasploit
        - nmap
        - john
        - mtr
        - jq
        - vi
